const express = require("express");
const router = express.Router();

const rootLogin = require("./routes/login");
const rootHome = require("./routes/home");
const rootEmpresas = require("./routes/empresas");
const rootPessoas = require("./routes/pessoas");
const rootProdutos = require("./routes/produtos");
const rootUsuarios = require("./routes/usuarios");
const rootPerfUsuarios = require("./routes/perf_usuarios");
const rootPermissoes = require("./routes/permissoes");
const rootVendedores = require("./routes/vendedores");
const rootCompras = require("./routes/compras");
const rootVendas = require("./routes/vendas");
const rootContas = require("./routes/contas");
const rootGrupos = require("./routes/grupos");
const rootMarcas = require("./routes/marcas");
const rootSecoes = require("./routes/secoes");
const rootUnidades = require("./routes/unidades");
const rootCidades = require("./routes/cidades");
const rootEstados = require("./routes/estados");
const rootTiposCadastros = require("./routes/tipos_cadastros");
const rootTiposPessoas = require("./routes/tipos_pessoas");
const rootAuditoria = require("./routes/auditoria");
const rootRelatorios = require("./routes/relatorios");

router.use("/", rootLogin);
router.use("/home", rootHome);
router.use("/empresas", rootEmpresas);
router.use("/pessoas", rootPessoas);
router.use("/produtos", rootProdutos);
router.use("/usuarios", rootUsuarios);
router.use("/perf_usuarios", rootPerfUsuarios);
router.use("/permissoes", rootPermissoes);
router.use("/vendedores", rootVendedores);
router.use("/compras", rootCompras);
router.use("/vendas", rootVendas);
router.use("/contas", rootContas);
router.use("/grupos", rootGrupos);
router.use("/marcas", rootMarcas);
router.use("/secoes", rootSecoes);
router.use("/unidades", rootUnidades);
router.use("/cidades", rootCidades);
router.use("/estados", rootEstados);
router.use("/tipos_cadastros", rootTiposCadastros);
router.use("/tipos_pessoas", rootTiposPessoas);
router.use("/auditoria", rootAuditoria);
router.use("/relatorios", rootRelatorios);

module.exports = router;
